/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#ffffff",
        "surface-dim": "#fcfcfc",
        "surface-bright": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#fff5f5",
        "surface-container": "#fee2e2",
        "surface-container-high": "#fca5a5",
        "surface-container-highest": "#f87171",
        "on-surface": "#18181b",
        "on-surface-variant": "#52525b",
        "inverse-surface": "#991b1b",
        "inverse-on-surface": "#ffffff",
        "outline": "#e4e4e7",
        "outline-variant": "#f4f4f5",
        "surface-tint": "#b91c1c",
        "primary": "#dc2626",
        "on-primary": "#ffffff",
        "primary-container": "#fee2e2",
        "on-primary-container": "#7f1d1d",
        "inverse-primary": "#fca5a5",
        "secondary": "#b91c1c",
        "on-secondary": "#ffffff",
        "secondary-container": "#fca5a5",
        "on-secondary-container": "#7f1d1d",
        "tertiary": "#ef4444",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#fef2f2",
        "on-tertiary-container": "#991b1b",
        "error": "#991b1b",
        "on-error": "#ffffff",
        "error-container": "#fee2e2",
        "on-error-container": "#7f1d1d",
        "background": "#ffffff",
        "on-background": "#18181b",
        "surface-variant": "#fff5f5",
        // Heritage Stitch / Sash Studio Design Tokens
        "sash-gold": "#735c00",
        "sash-gold-dark": "#574500",
        "sash-gold-light": "#fed65b",
        "sash-gold-accent": "#ffe088",
        "sash-black": "#1c1b1b",
        "sash-surface": "#fdf8f8",
        "sash-surface-low": "#f7f3f2",
        "sash-surface-container": "#f1edec",
        "sash-surface-high": "#ebe7e6",
        "sash-surface-highest": "#e5e2e1",
        "sash-kente-red": "#dc2626",
        "sash-kente-gold": "#eab308",
        "sash-kente-green": "#15803d",
      },
      fontFamily: {
        display: ["Poppins", "sans-serif"],
        headline: ["Poppins", "sans-serif"],
        body: ["Poppins", "sans-serif"],
        label: ["Poppins", "sans-serif"],
        embroidery: ["'Bebas Neue'", "cursive", "sans-serif"],
        montserrat: ["'Montserrat'", "sans-serif"],
        inter: ["'Inter'", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "4px",
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "40px",
        "2xl": "64px",
        "container-max": "1280px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "margin-desktop": "40px"
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(-4px) scale(0.96)' },
          '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
      },
      animation: {
        fadeIn: 'fadeIn 0.15s ease-out',
      }
    },
  },
  plugins: [],
}
